export const RESET_PASSWORD_SCREEN = "RESET_PASSWORD_SCREEN";
export const RESET_PASSWORD_SUCCESSFUL = "RESET_PASSWORD_SUCCESSFUL";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";
export const LOADING_RESET_PASSWORD = "LOADING_RESET_PASSWORD";
