export const LAST3TRANSACTIONS_SUCCESS = "LAST3TRANSACTIONS_SUCCESS";
export const GET_WALLET_BALANCE = "GET_WALLET_BALANCE";
export const HOME_FETCH_SUCCESS = "HOME_FETCH_SUCCESS";
export const HOME_FETCH_FAILURE = "HOME_FETCH_FAILURE";
export const NO_WALLET_CREATED = "NO_WALLET_CREATED";
