export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const LOGIN_USER_SUCCESSFUL = "LOGIN_USER_SUCCESSFUL";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_START = "LOGIN_START";
export const RESET_SIGNIN_SCREEN = "RESET_SIGNIN_SCREEN";
export const PROFILE_IMAGE_UPLOAD = "PROFILE_IMAGE_UPLOAD";
export const PROFILE_IMAGE_SUCCESSSFUL = "PROFILE_IMAGE_SUCCESSSFUL";
export const PROFILE_IMAGE_FAILED = "PROFILE_IMAGE_FAILED";