export const ACCOUNT_FETCH_SUCESS = "ACCOUNT_FETCH_SUCESS";
export const ACCOUNT_FETCH_FAILED = "ACCOUNT_FETCH_FAILED";
export const TRANSFER_TO_ACCOUNT_SUCCESS = "TRANSFER_TO_ACCOUNT_SUCCESS";
export const TRANSFER_TO_ACCOUNT_FAILED = "TRANSFER_TO_ACCOUNT_FAILED";
export const RESET_SCREEN = "RESET_SCREEN";
