export const REGISTER_USER_SUCCESSSFUL = "REGISTER_USER_SUCCESSSFUL";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
export const REGISTER_SAVE = "REGISTER_SAVE";
export const PASSWORD_NOT_SAME = "PASSWORD_NOT_SAME";
export const RESET_REGISTER_SCREEN = "RESET_REGISTER_SCREEN";
