export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_SAVE = "LOGIN_SAVE";
export const RESET_SIGNIN_SCREEN = "RESET_SIGNIN_SCREEN";
